Update azure-static-web-apps-lively-forest-0023e6310.yml

diff --git a/.github/workflows/azure-static-web-apps-lively-forest-0023e6310.yml b/.github/workflows/azure-static-web-apps-lively-forest-0023e6310.yml
--- a/.github/workflows/azure-static-web-apps-lively-forest-0023e6310.yml
+++ b/.github/workflows/azure-static-web-apps-lively-forest-0023e6310.yml
@@ -19,6 +19,16 @@ jobs:
         with:
           submodules: true
           lfs: false
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '16'
+      - name: Install Dependencies
+        run: npm install
+      - name: Lint and Build
+        run: |
+          npm run lint || true # Run lint without failing the build
+          CI=false npm run build # Build the project without treating warnings as errors
       - name: Build And Deploy
         id: builddeploy
         uses: Azure/static-web-apps-deploy@v1
